# Codemagic CI/CD Configuration for Orgullo Dominicano App
# Documentación: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  # ============================================
  # iOS App Store Build
  # ============================================
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.eturingsrl.orgullodominicano
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials  # Configura esto en Codemagic Dashboard
      vars:
        APP_STORE_APP_ID: "TU_APP_STORE_ID"  # Reemplaza con tu App ID de App Store Connect
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Generate app icons (using ios/icon.png without transparency)
        script: |
          dart run flutter_launcher_icons
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.2 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  # ============================================
  # iOS TestFlight Build (para pruebas)
  # ============================================
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.eturingsrl.orgullodominicano
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Generate app icons (using ios/icon.png without transparency)
        script: |
          dart run flutter_launcher_icons
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  # ============================================
  # Android Release Build
  # ============================================
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      android_signing:
        - orgullo_dominicano_keystore  # Configura esto en Codemagic Dashboard
      groups:
        - google_play_credentials  # Configura esto en Codemagic Dashboard
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build AAB
        script: |
          flutter build appbundle --release
    
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/mapping/release/mapping.txt
    
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
        submit_as_draft: true

  # ============================================
  # Build de desarrollo (sin firmar)
  # ============================================
  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.eturingsrl.orgullodominicano
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Flutter build ios
        script: |
          flutter build ios --debug --no-codesign
    
    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
